  service: serverless-http-api
  frameworkVersion: '3'
  custom:
    serverless-offline:
      # httpsProtocol: 'dev-certs'
      httpPort: 4000
  provider:
    name: aws
    runtime: nodejs14.x

  functions:
    hello:
      handler: app/routes/item/get.handler
      events:
        - http:
            path: /hello
            method: get
  plugins:
    - serverless-offline
    